#!/bin/env bash

# Vérification que le script est exécuté en tant que root
if [ "$EUID" -ne 0 ]; then
  echo "Ce script doit être exécuté en tant que root." >&2
  exit 1
fi

# Ajout ou modification de la résolution de localhost
if grep -q "^127.0.0.2.*localhost" /etc/hosts; then
  echo "localhost est déjà configuré pour 127.0.0.2"
else
  echo "127.0.0.2 localhost" >> /etc/hosts
  echo "Ajout de localhost -> 127.0.0.2"
fi

# Ajout ou modification de la résolution de facebook.com
if grep -q "8.8.8.8.*facebook.com" /etc/hosts; then
  echo "facebook.com est déjà configuré pour 8.8.8.8"
else
  echo "8.8.8.8 facebook.com" >> /etc/hosts
  echo "Ajout de facebook.com -> 8.8.8.8"
fi
