#!/usr/bin/env bash
# This script displays all active IPv4 IP addresses attached to the machine.

# Displays all active IPv4 addresses of the machine
ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' 
