#!/usr/bin/env bash
# Your Bash script displays active IPv4 IPs on the machine.

# Displays all active IPv4 addresses of the machine
ifconfig | grep -oP '(?<=inet\s)(\d{1,3}\.){3}\d{1,3}' | grep -v '^127\.'
